
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: false

providers:
  docker:
    watch: true
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "letsencrypt"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "example@example.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  format: common

tls:
  options:
    default:
      minVersion: VersionTLS12
